### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by jaikishantulswani** [dssg/repo-scraper#3]
Getting this after installing requirements
root@kali:~/repo-scraper# check-dir 
Traceback (most recent call last):
  File "/usr/local/bin/check-dir", line 4, in <module>
    __import__('pkg_resources').run_script('repo-scraper==0.1', 'check-dir')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/repo_scraper-0.1-py2.7.egg/EGG-INFO/scripts/check-dir", line 2, in <module>
    from repo_scraper.constants.extensions import *
ImportError: No module named constants.extensions

**Comment by pooja2508** [comment]
I also have seen the same error, please suggest how to resolve this ? 

root@UbuntuNTP:/var/Tools/Secrets/repo-scraper# check-dir 
Traceback (most recent call last):
  File "/usr/local/bin/check-dir", line 4, in <module>
    __import__('pkg_resources').run_script('repo-scraper==0.1', 'check-dir')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/repo_scraper-0.1-py2.7.egg/EGG-INFO/scripts/check-dir", line 2, in <module>
    from repo_scraper.constants.extensions import *
ImportError: No module named constants.extensions
root@UbuntuNTP:/var/Tools/Secrets/repo-scraper#

**Comment by AlekKras** [comment]
Just run `sudo python -m pip install extensions` to install it for Python2 and you will have that module. I do think that `requirements.txt` file should be updated though :)
